name: maelstrom_dart
version: 1.0.0
repository: https://github.com/orikerer/maelstrom-challenges

environment:
  sdk: '<4.0.0'

dependencies:
  json_annotation: ^4.8.1

dev_dependencies:
  json_serializable: ^6.6.2
  lints: ^5.0.0
  test: ^1.21.0
  build_runner: ^2.3.3

